server:
  port: 8888
spring:
  application:
    name: xxl-job-admin
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name:  oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
#      username: crm_owner_user
#      password: bss_crm_test
#      filters: stat,wall
################## mysql start ############################
      driver-class-name:  com.mysql.jdbc.Driver
      #     192.168.3.150   130.75.131.211  134.224.249.39
      url: jdbc:mysql://134.224.249.39:3306/iyydb_job?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: root
      password: root
      filters: stat,wall
  thymeleaf: 
    cache: false
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      output_encoding: UTF-8
      locale: zh_CN
      number_format: 0.##########     
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:s
      classic_compatible: true
      template_exception_handler: ignore  
    

mybatis:
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:com/xxl/**/dao/*.xml  
 

log:
  level:
    root: info
    com.xxl: debug
    com.open: debug
  maxsize: 30MB

   
 