spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile} 
  
server:
  port: 8070
  
logging:
  level:
    com.ctrip: INFO  

  
endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


