server:
  port: 11008
spring:
  application:
    name: zipkin-server-native
#去除控制台异常
management:
  metrics:
    web:
      server:
        auto-time-requests: false

#配置在数据库创建完以后，可以删除，不然每次都会寻找这个sql，耗费时间。
