server:
  port: 11008
spring:
  application:
    name: zipkin-server-mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zipkin_center?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    continueOnError: true
#去除控制台异常
management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  storage:
    type: mysql
sleuth:
  enabled: false






